apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: cloudnative-pg
      targetRevision: 0.27.1
  destination:
    name: in-cluster
    namespace: cloudnative-pg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # https://github.com/cloudnative-pg/charts/issues/325
    syncOptions:
      - ServerSideApply=true
