apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.13.0
      helm:
        valuesObject:
          controller:
            ingressClassResource:
              default: true
            service:
              annotations:
                service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
                service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
                service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
            allowSnippetAnnotations: true
            config:
              annotations-risk-level: Critical
  destination:
    name: in-cluster
    namespace: ingress-nginx-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
