apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-upgrade-controller
  namespace: argocd-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: http://charts.rancher.io
      chart: system-upgrade-controller
      targetRevision: 106.0.0
  destination:
    name: in-cluster
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s
  namespace: cattle-system
  labels:
    k3s-upgrade: server
spec:
  concurrency: 1
  # renovate: datasource=github-releases depName=k3s-io/k3s
  version: "v1.33.1+k3s1"
  nodeSelector:
    matchExpressions:
      - {key: node-role.kubernetes.io/control-plane, operator: Exists}
  serviceAccountName: system-upgrade-controller
  drain:
    force: true
    skipWaitForDeleteTimeout: 60
  upgrade:
    image: rancher/k3s-upgrade
