apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-upgrade-controller
  namespace: argocd-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: http://charts.rancher.io
      chart: system-upgrade-controller
      targetRevision: 106.0.0
  destination:
    name: in-cluster
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
