apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gatus
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: gatus
      app.kubernetes.io/name: gatus
