apiVersion: v1
kind: Secret
metadata:
    name: gatus-secrets
    namespace: default
type: Opaque
stringData:
    SERVICE_DOMAIN: ENC[AES256_GCM,data:yHEz6xdLiL4Ozbyp,iv:P3ANJSyHJWnT7OlCifqCZXzVsNnuFMWVAitVT08+mWU=,tag:KRqlMufETEejv28fASHcMw==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETHVBV1MwZXZyYkxrRkYw
            cDd1ZmM2NWxTSUxjUjhlQnBzUlFwVUtiL0NBCnZlRG1scnlodE9YaG9UNExEdUJl
            SDIzREdQdEs2M2NzbWF6NmdzUnNrWWMKLS0tIGtuelcvMXNFNXl2bnhXUUc4Qnlp
            Z3lqZ0VtU3k2aFBEc1NISGxaUHJjL28KeHGpJbgHGewQTgNRL3+T3lvbuDP1ZuY3
            bQGI668pWQV4/QzMJlBtNtr4RR+nAJ4aTe7wKoVJD2biNCXoXr0FbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-16T17:47:56Z"
    mac: ENC[AES256_GCM,data:uv4qx5ErXNy01ada40qJJB7LGd5FDU97/52Z7dqFGbVYsfraRm2ISgNXpd3755az2NiBlVy1pvzT2yxYUsUee2SCo967LeH4uDwCV/KS/eM8JcxKa2xtfoFvxc87NK0vfR7pWrKXCJnJ5c3WbzDV+hhHu2iYJiQEETVkhN/BC/Y=,iv:NXB4kKWUed6L+sY0JjOiCDrJV/JL53WxTQt51qRI1yU=,tag:r0R+B5E2Ww/nWr9fSMF9oQ==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: gatus-postgres-user
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:xmjv8ZQ=,iv:ZfK0gtYh1sAAV+kgEzySQlQbB1lFcr/Ky+giUMXfUZE=,tag:dtE7pZ2HB33J/Q380O/s8A==,type:str]
    password: ENC[AES256_GCM,data:3SFvNcNOegNReeqlUNolfA8/FxK8jEhNKM3iF8mF+Tk=,iv:uzalyrOL0HWu/xik6Guuv6gdDE/gBosqVjUg8xqtSak=,tag:cfZydrZs3lcCsa20EJ4spw==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETHVBV1MwZXZyYkxrRkYw
            cDd1ZmM2NWxTSUxjUjhlQnBzUlFwVUtiL0NBCnZlRG1scnlodE9YaG9UNExEdUJl
            SDIzREdQdEs2M2NzbWF6NmdzUnNrWWMKLS0tIGtuelcvMXNFNXl2bnhXUUc4Qnlp
            Z3lqZ0VtU3k2aFBEc1NISGxaUHJjL28KeHGpJbgHGewQTgNRL3+T3lvbuDP1ZuY3
            bQGI668pWQV4/QzMJlBtNtr4RR+nAJ4aTe7wKoVJD2biNCXoXr0FbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-16T17:47:56Z"
    mac: ENC[AES256_GCM,data:uv4qx5ErXNy01ada40qJJB7LGd5FDU97/52Z7dqFGbVYsfraRm2ISgNXpd3755az2NiBlVy1pvzT2yxYUsUee2SCo967LeH4uDwCV/KS/eM8JcxKa2xtfoFvxc87NK0vfR7pWrKXCJnJ5c3WbzDV+hhHu2iYJiQEETVkhN/BC/Y=,iv:NXB4kKWUed6L+sY0JjOiCDrJV/JL53WxTQt51qRI1yU=,tag:r0R+B5E2Ww/nWr9fSMF9oQ==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.10.2
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: gatus-config
    namespace: default
data:
    custom.yaml: ENC[AES256_GCM,data:6OZnhJkON8Yz2LnA8q1C5f1LJVQX9nGTTttkcfOPinNt9yvAF4x+wJzZGW0qvPvPRXZThouBwL2ZhjPDuNnWEfoAJ+AbdeAfy9LjhiVlCh2xiTtiUnOjb26HCtHeryHZnBjeXITKfy4oWeBB32YF6z4q3NDISa6eyhVDvySdStX/0oTBDdvwjQRIrBsEB3r1szVN0UqmgbTq7PuhziQ3CGHQ5kPPmEJOJe2oxmn/MIOD3sRhXBlGBfSprEZQngHm+p2MPUwRmyj5VZbMDY9fGOYIHpJewR4Aiy6/1UU59WhzzI+JW7AwNXOlYV4z20fFRzQoAg0dB76/a2BNfSG02gH2CpHiNYcnlPd1cfTP88RCrFTjV3DHrWoiLk87ZxMfOl8XvrgMc5h/52zSDv6Vu3F9FQ2SCMYoZ0Wr52wwZKktMVhPFTIoID1ZOBORs4UHqCRKFN9QZEMejTqIRFQsU7ZmyTqeT1+2ubNXjjsugRB6mh1dFN42n+uUy+FdYp8Hv+Oqn2KRMM2wqe23zHr4wfS1vjH8Mgzz79utCtALJAIq6NPN77iVHRWX2vrOQ+pr09AFh4TbBAE4C5Z9MVDPWyP/2UddZAJ98RvLDiWo7B8Iumwk4QmEW0RDRhQ5zSjn8lfDSbCwNcT/e3yRF/I8lDqxPAfi5yTkag/l2hStqrQMXK82zvtAKPdhYQaMjXyyTYsv5LyQL3QyQcpNiLtMKfzH7ntmTFChqQN/Bf0/vv6IAGjpn2TM33Pf7pWeIOeyQ3F6ghxLSUo9V9gX3UNT0UTee4dI0mhtpY2oPvuG4hNNSIW+29Sn9ToMao8c2P1YMNbVHtg3DD9MhEyxivuyRfLqwoZIh+MoHh22VMXwn06E0w+4C+DFpHfBDRm0AcG1PdwByJN3oa2TVnDaRTWrplKCWFdhCVVusFFt/00qd95dXaT+WaLtRe81Wa/TyOO+XlTvcNbtIdtIOJKihdmcaB1sbXUyNvZrpPo+4fIWRYf5QOSkW85+Xp4zLJvU58+HF4/W45Ee2aoHrQ9d/EtqibqEBrsvwAplA1jXZJ8YOdi2Aabi0d8AALy1qFA/PsxMJ+l3PyL83ApK4AZeKyvLyuYnxKpzNb9cDuP5skPIDJRRyG6uFyUs7Ks36gsqa2DVOGpFd4Ruvi7wfOU89UOOzHiJse+cIxZEFekxecBlbrrVzI/3oCIYrOzumc9fCOiWQRPthPLC4hWGAdXBSKqVWARdK36xa21lL9VANOugVnYyb9XxgykrSH13jqAxBRpZHAy/hk/HpJj8MBDyqMRpZ0QTMzTKpYB4u7HpnI3TTWDqQ31OzjLLNcsJ40X15HXmftme/2hmT0BsEZfdtKqCr5IWtbkiSxsCIyEGJOaYUuC7LXPF83Xkda1jrgxknd/tdgx1TdV2pa3z+s+fiQTXXNWHHZrZOpRQgpi6E7P75lkbio1Ih08axnyKDzCz4vE5ExKQrSiHBWFaI8CGn3aio+iPay9sg9djYAb1TLKU3rImJ6E5RYMcbTN/eTOxwkVTDnv5yCfMAv3cYEDzIpBoMmQpLkPauTayQMDZ2JaU8knRyMwtGLy36eJML0zILmrxK9I9DGYXS4VS5XmCp0w+VjlW96y/xNEq+5I/zYjvokL0/kKyhEBSUCjiZIXvYBKYO9iTbRQstVlO67jOxWz6upepF/J7CttwX6SD8dNxKSdcei0G1Lui6NefBS8Q39u9u57aWzoQweNMvTU02t+PMqDbEMpgJMxwKlreNc7IN+wHfxV9EdWlh+D+Zh1/b34ljBEvDW3Gx6VtH7k5DqThWCVxh+h70x4Wa3CmnULB2JZOaLgPpzszHJYDfp6bPAHTV6EevUVdSz0jWPEBXaJT4xAYIfMWw0V2khEUdpGLRPZyX3T+M7RR1jy+DRVvS5SAOUy3crUOK1S5qp+hikCgWiTsFv2SBaFxoqiRnjihzqTexVDg/G9eWwAWl3rf9a9abhOt6vO9juFbFpE0EdMyJxkz1Pyo+uo99cZOK+RDv+RMSm2vupkfw2p345Nf0VtxAui5qXLNiSD5p1c73uX37DuQExfcndFISLJCr/Pl0Qsek2ZL3+JnCx/ZOVPhMgPXXnFhTWIYleuFqwEZzNE9rl8CM6xyv/69+Xjc/xyD/tlNVabgKAm1jJ/reAB3RtcHTIujB65foR2FTVL5xzVKZaFjNYkcpl8yzFOBw4fRI3j564z+T2lGTnMmrERN6vqFzLvOFQDHdct74Aottq9cyO3oRvUx06CAEitseLBFQEmtq2braIPi8wuoeXtShRnGQxHb0xqEOFETapuT8mFWXzXfxesDLw80T7TBEFzK1O8vNuqBBtb0RoiayKa/xZvFPKARNBakdfjKRg4euArZ4wKWlaDt3Q6Rbj/OaZS/8QVago+DkvwVYwsT5XFPDT14+m2BugMBz7UcZdjxDv0++vWmSNnOOlGdVO5wA/fhj+Tz82WJj105AtwZdcGjbgRdyZsiVPM/tWonXaCvteiMmcqyYRIRCLic6IksSjeZ9nMcUJ8SUR3X7mVAm+HwhTjWWsmXcV5hfj7ZbaroudtS6HfEnMr5kNy/CKvt7t8MehVL65/JayZlp1tYxAgOlyVJYKyZr8F0ffcQWEw9bFSATdgfiQMIm9B+CRgNcMs6hAQ0Ik2qrHQQzA6PGmAbnMuFK61q5+omEUksY7Vow3wjSo96dK2BKqWan7pAcPRvZpiZFCaF1/bIcVJqTOi7qe2RZQ7SKpU3cbTM0kZw/c/KAk2mvY0CakFoY7KrOLjMxr/Pu9Tii44GX/jokJbOIgG3uB3BRVSGEWQGevVknmcHHtdFlx4ScmSk5yKHIRuwVL4lwKu3RbE10ccGMrssVzmdS7RUeZF6OGqd59iP6MxB1JUwVMXB3r2gRI8CaVddYp0=,iv:tM32jSerc7LCvAy3Uq7il3i7EIQxLOTQGy8PJyDLHzc=,tag:bToZVAtWEBtuPOqPU5WY3g==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETHVBV1MwZXZyYkxrRkYw
            cDd1ZmM2NWxTSUxjUjhlQnBzUlFwVUtiL0NBCnZlRG1scnlodE9YaG9UNExEdUJl
            SDIzREdQdEs2M2NzbWF6NmdzUnNrWWMKLS0tIGtuelcvMXNFNXl2bnhXUUc4Qnlp
            Z3lqZ0VtU3k2aFBEc1NISGxaUHJjL28KeHGpJbgHGewQTgNRL3+T3lvbuDP1ZuY3
            bQGI668pWQV4/QzMJlBtNtr4RR+nAJ4aTe7wKoVJD2biNCXoXr0FbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-16T17:47:56Z"
    mac: ENC[AES256_GCM,data:uv4qx5ErXNy01ada40qJJB7LGd5FDU97/52Z7dqFGbVYsfraRm2ISgNXpd3755az2NiBlVy1pvzT2yxYUsUee2SCo967LeH4uDwCV/KS/eM8JcxKa2xtfoFvxc87NK0vfR7pWrKXCJnJ5c3WbzDV+hhHu2iYJiQEETVkhN/BC/Y=,iv:NXB4kKWUed6L+sY0JjOiCDrJV/JL53WxTQt51qRI1yU=,tag:r0R+B5E2Ww/nWr9fSMF9oQ==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.10.2
