apiVersion: v1
kind: Secret
metadata:
    name: gatus-secrets
    namespace: default
type: Opaque
stringData:
    SERVICE_DOMAIN: ENC[AES256_GCM,data:yHEz6xdLiL4Ozbyp,iv:P3ANJSyHJWnT7OlCifqCZXzVsNnuFMWVAitVT08+mWU=,tag:KRqlMufETEejv28fASHcMw==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETHVBV1MwZXZyYkxrRkYw
            cDd1ZmM2NWxTSUxjUjhlQnBzUlFwVUtiL0NBCnZlRG1scnlodE9YaG9UNExEdUJl
            SDIzREdQdEs2M2NzbWF6NmdzUnNrWWMKLS0tIGtuelcvMXNFNXl2bnhXUUc4Qnlp
            Z3lqZ0VtU3k2aFBEc1NISGxaUHJjL28KeHGpJbgHGewQTgNRL3+T3lvbuDP1ZuY3
            bQGI668pWQV4/QzMJlBtNtr4RR+nAJ4aTe7wKoVJD2biNCXoXr0FbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-16T05:30:08Z"
    mac: ENC[AES256_GCM,data:7aeXju/3iRMoKcPqoOd+XelOLgv5/jtg7G9P7XGLecUk1aIT1QYKwrj9zS3+qDjAEUAU2vNUwv9IWe3wtYyj8mK+7uv/U1x17qqi909L7y0Wm0B1cTl62x22C9RUvxweaWMCDUASVcf6jtRB8LBg2RJ7wa87w9RuSH5ZR9bBrW8=,iv:Pypxj+UrxIMSPbYmMBUEVGhZyYpKckPxCH23VfLimOU=,tag:8jwO+GJjQSOiSfoQ2Jcw2g==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: gatus-postgres-user
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:xmjv8ZQ=,iv:ZfK0gtYh1sAAV+kgEzySQlQbB1lFcr/Ky+giUMXfUZE=,tag:dtE7pZ2HB33J/Q380O/s8A==,type:str]
    password: ENC[AES256_GCM,data:3SFvNcNOegNReeqlUNolfA8/FxK8jEhNKM3iF8mF+Tk=,iv:uzalyrOL0HWu/xik6Guuv6gdDE/gBosqVjUg8xqtSak=,tag:cfZydrZs3lcCsa20EJ4spw==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETHVBV1MwZXZyYkxrRkYw
            cDd1ZmM2NWxTSUxjUjhlQnBzUlFwVUtiL0NBCnZlRG1scnlodE9YaG9UNExEdUJl
            SDIzREdQdEs2M2NzbWF6NmdzUnNrWWMKLS0tIGtuelcvMXNFNXl2bnhXUUc4Qnlp
            Z3lqZ0VtU3k2aFBEc1NISGxaUHJjL28KeHGpJbgHGewQTgNRL3+T3lvbuDP1ZuY3
            bQGI668pWQV4/QzMJlBtNtr4RR+nAJ4aTe7wKoVJD2biNCXoXr0FbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-16T05:30:08Z"
    mac: ENC[AES256_GCM,data:7aeXju/3iRMoKcPqoOd+XelOLgv5/jtg7G9P7XGLecUk1aIT1QYKwrj9zS3+qDjAEUAU2vNUwv9IWe3wtYyj8mK+7uv/U1x17qqi909L7y0Wm0B1cTl62x22C9RUvxweaWMCDUASVcf6jtRB8LBg2RJ7wa87w9RuSH5ZR9bBrW8=,iv:Pypxj+UrxIMSPbYmMBUEVGhZyYpKckPxCH23VfLimOU=,tag:8jwO+GJjQSOiSfoQ2Jcw2g==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.10.2
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: gatus-config
    namespace: default
data:
    custom.yaml: ENC[AES256_GCM,data:xZI1ZKWuMwHG9RLGcQmq707HrRiAy9XhaqsT0o61jbRQGkR223QTsvup0s9P3kIdnnlcaEWgunM+Gk9aKAGWp5ciSQbYcN9zQLfCQaa+2KP4wKTXiKw4BWtQSmWuSo3BD9Qo8hCj53uAbww6EDPeBdfEutW7tJ1dPlM3fJU+XwNP+WEv1aWERxS93WpUD3RyRR5nH/rPXi4hkc5da/dQv9IWlOxQSm2b0F4CDe2i8igZK/htKyg2p+b6aakPk6AzoxF/YtgfLmSd+jsdDhIXb3BjmgTN8gbB9vvuQJCEwT2Pg+CKwM5O/HzQNOCKrgGS7STIPNNr/NRSllwH6lkghlMEuet2Eu4nqWD+ppPbDoD8jQLklDxBGt8sXDMeWaN8ajCSOZP8X5Nb7iW6Vgu/9jvDqgEHpYCncan8bqou40oVGBrY5uXbCXSfnMrHM3p/OyYhg/V1uUgbCIgT7Cp0DvNPAYv+h9+dcKqIAQTCyoQ9F6ebv/dX1N3ORsXu4cjg0oPD3Lz8VAC7Gw7XQbEtTrsIV+gBIyMM5rse1zgOta1n4tC3/NvJPQrKVJzJtBixv7ZK+00hwwnCJ7M5y3nVCIeNlbK1htLR8kC90odD1fnbr3XHSqv93TQ7jn1ii6VPd1UDteUcmuoUlPBR7aXHaLLFLI6Q05FNTCKAIItFsRgTPCKNpe4zRwsNVM295BdAhC/fF+bN+afOOjW3fiI2eIxv2e6v6k/n5JA=,iv:jmkWv/H4+d+WZeLrtGu+aBzO9Wz4v0olePEYfm+urng=,tag:2tZ09Bsyecn6sqJ3F2fUQg==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETHVBV1MwZXZyYkxrRkYw
            cDd1ZmM2NWxTSUxjUjhlQnBzUlFwVUtiL0NBCnZlRG1scnlodE9YaG9UNExEdUJl
            SDIzREdQdEs2M2NzbWF6NmdzUnNrWWMKLS0tIGtuelcvMXNFNXl2bnhXUUc4Qnlp
            Z3lqZ0VtU3k2aFBEc1NISGxaUHJjL28KeHGpJbgHGewQTgNRL3+T3lvbuDP1ZuY3
            bQGI668pWQV4/QzMJlBtNtr4RR+nAJ4aTe7wKoVJD2biNCXoXr0FbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-16T05:30:08Z"
    mac: ENC[AES256_GCM,data:7aeXju/3iRMoKcPqoOd+XelOLgv5/jtg7G9P7XGLecUk1aIT1QYKwrj9zS3+qDjAEUAU2vNUwv9IWe3wtYyj8mK+7uv/U1x17qqi909L7y0Wm0B1cTl62x22C9RUvxweaWMCDUASVcf6jtRB8LBg2RJ7wa87w9RuSH5ZR9bBrW8=,iv:Pypxj+UrxIMSPbYmMBUEVGhZyYpKckPxCH23VfLimOU=,tag:8jwO+GJjQSOiSfoQ2Jcw2g==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.10.2
