apiVersion: v1
kind: Secret
metadata:
    name: gatus-secrets
    namespace: default
type: Opaque
stringData:
    SERVICE_DOMAIN: ENC[AES256_GCM,data:yHEz6xdLiL4Ozbyp,iv:P3ANJSyHJWnT7OlCifqCZXzVsNnuFMWVAitVT08+mWU=,tag:KRqlMufETEejv28fASHcMw==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETHVBV1MwZXZyYkxrRkYw
            cDd1ZmM2NWxTSUxjUjhlQnBzUlFwVUtiL0NBCnZlRG1scnlodE9YaG9UNExEdUJl
            SDIzREdQdEs2M2NzbWF6NmdzUnNrWWMKLS0tIGtuelcvMXNFNXl2bnhXUUc4Qnlp
            Z3lqZ0VtU3k2aFBEc1NISGxaUHJjL28KeHGpJbgHGewQTgNRL3+T3lvbuDP1ZuY3
            bQGI668pWQV4/QzMJlBtNtr4RR+nAJ4aTe7wKoVJD2biNCXoXr0FbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-23T19:34:23Z"
    mac: ENC[AES256_GCM,data:u4PLr2goPyfzq2fplda1n1MBQVuRiWoe7ho9tO1DVyOG4bkXQRaILL5EPbAxYbCw3uMHkqOphjqeFNXhFhk/JsX7/m7dAqAhkGdOYAOyRoAxVIrEoAivMS8N/mpG1gpQDOA7aen041swBG7OInW9x5FJNd97m2ZkKwDKTnRGJfE=,iv:c0KNmHdsCfYUx0YCRUNWR58h+bahqtrOYVlWL4bA8Ow=,tag:ygTlj2WKJikT130MJb1ymw==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: gatus-postgres-user
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:xmjv8ZQ=,iv:ZfK0gtYh1sAAV+kgEzySQlQbB1lFcr/Ky+giUMXfUZE=,tag:dtE7pZ2HB33J/Q380O/s8A==,type:str]
    password: ENC[AES256_GCM,data:3SFvNcNOegNReeqlUNolfA8/FxK8jEhNKM3iF8mF+Tk=,iv:uzalyrOL0HWu/xik6Guuv6gdDE/gBosqVjUg8xqtSak=,tag:cfZydrZs3lcCsa20EJ4spw==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETHVBV1MwZXZyYkxrRkYw
            cDd1ZmM2NWxTSUxjUjhlQnBzUlFwVUtiL0NBCnZlRG1scnlodE9YaG9UNExEdUJl
            SDIzREdQdEs2M2NzbWF6NmdzUnNrWWMKLS0tIGtuelcvMXNFNXl2bnhXUUc4Qnlp
            Z3lqZ0VtU3k2aFBEc1NISGxaUHJjL28KeHGpJbgHGewQTgNRL3+T3lvbuDP1ZuY3
            bQGI668pWQV4/QzMJlBtNtr4RR+nAJ4aTe7wKoVJD2biNCXoXr0FbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-23T19:34:23Z"
    mac: ENC[AES256_GCM,data:u4PLr2goPyfzq2fplda1n1MBQVuRiWoe7ho9tO1DVyOG4bkXQRaILL5EPbAxYbCw3uMHkqOphjqeFNXhFhk/JsX7/m7dAqAhkGdOYAOyRoAxVIrEoAivMS8N/mpG1gpQDOA7aen041swBG7OInW9x5FJNd97m2ZkKwDKTnRGJfE=,iv:c0KNmHdsCfYUx0YCRUNWR58h+bahqtrOYVlWL4bA8Ow=,tag:ygTlj2WKJikT130MJb1ymw==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.10.2
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: gatus-config
    namespace: default
data:
    custom.yaml: ENC[AES256_GCM,data:Wo3GEx2/SVtNSZjrCByzsxXZhoMfXHe/3hhyLx/LhSOiNY8C5YG9OuC2cLUZjP6Eb1Gcbp/mKRWfeGyevl4OGJUMP2xy6aYFtCn8i6f9Jhf0GyStFEEHVWpTggr8b+E4ISgth/HilN+Quyd1GDA7kMd8yzJnmErqHWoZjd6Guz3viXXSX1CrUPeioPo27OF8X9ytArVSamgH4vQg0+7P6bgJZlTBGdPVBi7THbBagzgclSXBRIp/e1ib0ZNGUKKzo2Zq8G6CTN68oSK9akycaJbahJKh/rUJMLiTwmLIkkJ+IamBjisa2jFZfX929OKur7L8kFBV+ic7xgtwhKtX6lcD1M/bB76xuTPdNbfvNQGM4jTSx6V1/E4FtWTFNKxbrvgiVo6jInD0zB1fJq5TQmrYMRObz2Z6Adbi4J6CqhgeeoI/5n6dhyP7q0owlu02JUY5MwHqidOtM6NQIXmCdRBz56e7DvSGW8MdHzaw0uzY1UYDnDQ8UsRZxHUfHmki3SyjW4tCZAiFfUOKoBMOGeGFkjKm7WqI9z58Ejffz9wKMoNJFrHcE0/XV7s4qo7RK380PdZXLM/BuFoh1xoOl4umHftcXy6BPpbWBLo4IIvl9NxLEWbglaaj3U2dMnhuD+CFzF0wYeK6ZJGzvOc2qao8/c4h5ASOoeExMygjep4UqsRAuQhcjM3Cfszc9bDwNsvVuBJgwBI6PxtA8LHxUX4nlqpJ0mjL2xK6H+Q9sSnyw+UGpeCBvTANFN9rW5xrzbC583bzzKm/UELxPqAXPCBwkUIM5uvdg1jQ/JvJhxwiwwpDiYQ/pq5uK2StgtA+9l3drcZFIM58aiCrtFPVgQrB1Sgd2WLj1YI6RCkPMOl4fftSC2cld22aVOEfiKumWVWojuTPkW1BA0SXBUXw7+ZJlcw4AnSFXqd57LMObUDXUJRf1I03Ls7X6DJiIH4nY0kAsUxDhM9E2WET13lnjf0H1C+xMHj2mwGY/2TdzcP0WRSPABWlqOH+cUaFX5AOprMsLFBlh9y9RALAELuQOVL+9J3WOekXLf1Pp3oBNHPG9hRvvX0goGXWicznG/LTCC3JLm4UDbiVql3lW7EhgpILtd9Jl+ViH2BUDf+kOMsxE4JEeQMnpzhTnqDGgRR383Co37dUnO+piOjYjh5vHRse8rsAGUmeH8OqKbUZgn1ll/hGKVUtwGRF1R6APzH65cEHiV3+ENGPQ58TVuWCVg8qOyo5sWii2xen5wnGKtPXGHm1R3Rq9VvnZUXrfqYa475k8ijD0SIOPCO9LGblnBx97oigzQVDVbGskfM+C5d0BMcQrNypb+DMXJ9QiLQj0UK8B0bGMW9KRcdcXcg3nsg0ZuqgATX0SQLT8LzVySHruI9SXoSfFW7KhxqzdrF6/XNPpg/8/peYjlOrfdzVqlLZcXeb6BswyOOqDHm9FeZo7h5JwvscTT+b4df6GnMmi/BAlCgQM1CBrpYLs1cb7ewmGNhGO3XjmeOIn0H7pvl/58LbwsgE9Pj/3MnqFTYAGum2LXTfx2dOo5XLqmV/vSviCbT9C8OhpFiAHE6R9q2Avq65GvjH0uVnTu0St41b/rkihN4blnTOI/Xr3JpE72sQFoPzCBcnsEJQgsVNdEA2/1UCIaiLYy1QHT1cVlbygwUrWgykneX9dftjXHH/IUjxMoXAGEEhpeijg2eW0l4GdTumEQ4rAjQAgxatLnZBdM65ufbMURovo9gTWRrJGwb5qhm/fx7Ndn4gDn/oIpa63KbpOxhu/Y6Vvi/YeL+RUurZauTfw+QPmc2BMQSsQuTATJWeCcyKhNqXyASs6KpnGnpn1YA3xPptzx7jDYUBLPlvAJPZr8Pj4XQGJGuxW8t2Ls9MUyG/4aY+NNAfETKe+ej7FNKYeBElCsQguMLVh+tEzq/w8f0x2NtpMlJx+7KFVrv+xJ++ODA95eKPQHyfRMWbxT0HZZ39ANM6PbYHK0Fr/csRcjwth5IePsUl1iDpsFV6qqI7//wRvoVbw3CSbiaCjRDUCQmkPASDzG+owie0C5YDPgL0zTEVQDHLXNuxzZ7pug4E6UeSDkv9uB33yFcupYRD3k2E29+hYAnaN7PcuZsAZ1jUN1aTfM7xkjbZNEaEg5K9Pg+vrBw9Hgmg6ycpuA3CRi47oBWJPz0blz1SQx1bOsLvFcaYjhn463sT64/QsVPOTpHu2ObbfBi54+gxrkM5av8OF7F3c/EX0u+nc65awFHfeOJncEQ2MXpdjyhTUV7RkHTPbVotp8R92/7qm3WNAxSWR/ZeJ334OEFI1+FbmlQzQd6ETSJzhR2sJgBw860YBXTSWcF5E94PF5poB7La46B8Yo0oHqNVrYfXjSjAfbHs/0zp2PS631q8HK4av6vsHD4rQmX/1pjPNTYVWQ0kUrEih50h33GhFuit2AQD3E3lGfP/v+ngKwistI+KXDQrfNZVEgY8aR0v6r09ngmYH/xiIu2bR8JCQH6GwCYoRHqjJbY+Tu+Ogqwi9T6riedSlEFLLk4uMecv8Rg3ebAsiaWoaqC2QQfJ9eM4/GVIL9KzclrEm4BWnoSxwaL2gFSIBUet7BQkQjmYGWAng/1z7lp/+lqOw57UJln5Jnpw8u5deAjYN23hl8JYNSLyHFjcWae8JGGj7EtFlpECZTwUbIcpSal8sCAlJL5knN2oan4F0HkTUTJ0Mj0nPf/CAkn4TBDCA6uze+SkkVbecxZ90Vd8zjFqISOLpajeAvBJioBnOVoB7hjltm8a4a3nE/zr4tN29jxKzGBguQEadD7RLdxuE7XkuiaJy+cD0QBh4PFXB2TSxS2vMbR8WB7+z9IK+GoUh7PBr9/qQ013c0qLJTRjQ1ldWHaDotyxjX7R0YOfP+M0+LcDBd5mphGqIm6wZMKH55DOgnGBVCxx6rgBNNpv04XgfYlM9rCRZJUZK1DTwIXV7TojeAV8LhworsQcegEb6ApsSzs+qBynlcakbPWTiTGrlQ1ffod5uw8r2jxWtKxXkgWvMhzb5IXorTLYPr7lAALPaq61YyeaKD34SeQI0/k/WH9kFcPLaQFpGNEwqhGGP1y7GVUfHJhktcNMWcVukiptgO6FMhuYfdSEGH3jQxbNaYCeGXkhM5xfQjum0E7sMO8wh0coBSvfCa9wB+EjEBP5IfFAi1908ZkJVpK7t+oPhp/3U45PEEVal5fSI5uRHPwPoyc6JsEaClSI6upVR0LZ3Zr/I5LMTFGpKEnakmvkgDtKkARSRXuhelQdLiX4P9ebIoZe8aLtQAMFOrR8l/s2ZjKqNTwgcl7pL4M0clBDozFQnaq4nLyiXxJTDKc0w/DQ7HPBmeQX7iYUSO0N5U9F0Y8Q7ndtNxWpQMmOk+C0O032JrRq/h2RHzDu4vIgZHnMMBOTMSjF2eSHdxk4UykMyXbbY1HGTcCw8W4jViqDs5ngWHQfx5ZsZ/Mn7UZrU/CLoXiZP/+OsTsWHW49rwm51d51r359gnZcZOjy9Hs6fMaT8rdjEoaEIFgdzChrmbdDg8GF1/7VarWVF+umR+StZGiGLeZuZPoK4SX+cFwFUWHQIFJlkq+Stv3FPf8O8PBBYEAefnfDiQQVH//9VdIiLoLOGrlqj/EZE0Im6fl9l76dnA/HvLiUvLxlj6rLIVh/MWsEZ1D3/gecxXs+XaV4ckb1QXwfFX7rbfVGVg6x1ICuSVJB/+dP2MYv9oifTsH9mFxM/rVTCdaRZr6YI+2IieOqORL4KZwieL1vNyjAFQwAOZsWLBmfWJSG3/Q4g3YcTjOjAm7RLdObFNb6MYZAUN1/Q3f/gH8c3BoIel0a7fZHf5zXKVW2Le82zLTr4yq+SJNN/zzj6L0pNhRXWjIfe8zMBPmqbChcpKqalqWHIAjyKGxiAqzG3zwj/gLl5iue5Md3B9oe1PS3Y/MsXQVsbuyNVh/I2zYu1JQgC/MX2JjJ4KveOCJraldV+gqNVaR6xYxaonIihiVKArb469y/p2Xbl7pQGu22uiWn5yjLgCyZdBvMtKQV5psGKvD7yDBpUpSndwpNsZMnQn2ZS4ZPSPm+n1G4g97D86tP0l4XnjJpxP1bpy/u12JP0AI+taTHg0jSN2Zxl17/kLq1Xy4emuJqqs9kVUB5zx7an2YT2BLZDvQRJoMDJTcKL9SpU/LPeSIvqCWXJVgEgdgMy583f6/T5qGJ2yytOjCk5h1IiO7sGIzfucgWGp/EjYhT9Ji05F1pRU/Fe9PZsY/NNkkCPw+y1o9i1O1/U/n16JJx,iv:ots13MdRQPpethlgSFMp2DX8L/f1DFNatIjR3Q5I/hk=,tag:LwA5I/C7M8DEZ4o7SkTIcQ==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETHVBV1MwZXZyYkxrRkYw
            cDd1ZmM2NWxTSUxjUjhlQnBzUlFwVUtiL0NBCnZlRG1scnlodE9YaG9UNExEdUJl
            SDIzREdQdEs2M2NzbWF6NmdzUnNrWWMKLS0tIGtuelcvMXNFNXl2bnhXUUc4Qnlp
            Z3lqZ0VtU3k2aFBEc1NISGxaUHJjL28KeHGpJbgHGewQTgNRL3+T3lvbuDP1ZuY3
            bQGI668pWQV4/QzMJlBtNtr4RR+nAJ4aTe7wKoVJD2biNCXoXr0FbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-23T19:34:23Z"
    mac: ENC[AES256_GCM,data:u4PLr2goPyfzq2fplda1n1MBQVuRiWoe7ho9tO1DVyOG4bkXQRaILL5EPbAxYbCw3uMHkqOphjqeFNXhFhk/JsX7/m7dAqAhkGdOYAOyRoAxVIrEoAivMS8N/mpG1gpQDOA7aen041swBG7OInW9x5FJNd97m2ZkKwDKTnRGJfE=,iv:c0KNmHdsCfYUx0YCRUNWR58h+bahqtrOYVlWL4bA8Ow=,tag:ygTlj2WKJikT130MJb1ymw==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.10.2
