apiVersion: v1
kind: Secret
metadata:
    name: gatus-secrets
    namespace: default
type: Opaque
stringData:
    SERVICE_DOMAIN: ENC[AES256_GCM,data:yHEz6xdLiL4Ozbyp,iv:P3ANJSyHJWnT7OlCifqCZXzVsNnuFMWVAitVT08+mWU=,tag:KRqlMufETEejv28fASHcMw==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETHVBV1MwZXZyYkxrRkYw
            cDd1ZmM2NWxTSUxjUjhlQnBzUlFwVUtiL0NBCnZlRG1scnlodE9YaG9UNExEdUJl
            SDIzREdQdEs2M2NzbWF6NmdzUnNrWWMKLS0tIGtuelcvMXNFNXl2bnhXUUc4Qnlp
            Z3lqZ0VtU3k2aFBEc1NISGxaUHJjL28KeHGpJbgHGewQTgNRL3+T3lvbuDP1ZuY3
            bQGI668pWQV4/QzMJlBtNtr4RR+nAJ4aTe7wKoVJD2biNCXoXr0FbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-17T06:10:48Z"
    mac: ENC[AES256_GCM,data:xbLVZKYFwqA4/UpFCSdyR1e44iHGFAwmqxZd3o3TiMj9soCcXEXZ7WQYBO9dbo+DCxgMSyQQsHDyuIXwErXYctHJPQFxuH3q9XohRvfg7A+3j62a9M76SE0/r1BXYaogNXP1oXUySRDpnvH4Zca2+82ksYVO1jSx93si98AET6I=,iv:xg9+E2dfZfQmQwz1RpqwLkZMR6f/zQLpxqhuT4EXy4Y=,tag:6SNV4+8hP67OIeV/kot1+w==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: gatus-postgres-user
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:xmjv8ZQ=,iv:ZfK0gtYh1sAAV+kgEzySQlQbB1lFcr/Ky+giUMXfUZE=,tag:dtE7pZ2HB33J/Q380O/s8A==,type:str]
    password: ENC[AES256_GCM,data:3SFvNcNOegNReeqlUNolfA8/FxK8jEhNKM3iF8mF+Tk=,iv:uzalyrOL0HWu/xik6Guuv6gdDE/gBosqVjUg8xqtSak=,tag:cfZydrZs3lcCsa20EJ4spw==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETHVBV1MwZXZyYkxrRkYw
            cDd1ZmM2NWxTSUxjUjhlQnBzUlFwVUtiL0NBCnZlRG1scnlodE9YaG9UNExEdUJl
            SDIzREdQdEs2M2NzbWF6NmdzUnNrWWMKLS0tIGtuelcvMXNFNXl2bnhXUUc4Qnlp
            Z3lqZ0VtU3k2aFBEc1NISGxaUHJjL28KeHGpJbgHGewQTgNRL3+T3lvbuDP1ZuY3
            bQGI668pWQV4/QzMJlBtNtr4RR+nAJ4aTe7wKoVJD2biNCXoXr0FbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-17T06:10:48Z"
    mac: ENC[AES256_GCM,data:xbLVZKYFwqA4/UpFCSdyR1e44iHGFAwmqxZd3o3TiMj9soCcXEXZ7WQYBO9dbo+DCxgMSyQQsHDyuIXwErXYctHJPQFxuH3q9XohRvfg7A+3j62a9M76SE0/r1BXYaogNXP1oXUySRDpnvH4Zca2+82ksYVO1jSx93si98AET6I=,iv:xg9+E2dfZfQmQwz1RpqwLkZMR6f/zQLpxqhuT4EXy4Y=,tag:6SNV4+8hP67OIeV/kot1+w==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.10.2
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: gatus-config
    namespace: default
data:
    custom.yaml: ENC[AES256_GCM,data:eLs2TIqewaBkrVmm+dzmBGgyd0nMAC0KFC+8EDxfy0v+ArIhdNHx7eEgOc28mYMvPWPU6DkjD7KEPSit78UichFwAypWG0KVULkNkUWN693Hy8mw7CtiyT/+DtMmHVchxP+Nh47eC118vKPhuTlnxlmbpG5T2s6TcgccqhTvwbTRth+OInFWnPShd73p2HfqIGbqWb2/3CoBsLnw9TVL7KNmbBH1OGxnHt1N+v9FDd3Z7sMAul6pPyGffwh/ULpnUnM/NkbYNWCleUpF7TqrdMU2FWgjKdFpego/Snj0Qn3durzEOK72WRZrbZVmbADsfKQvfLKQkUrgoEVjnGaxj9pSjH8rs/To8El6fQSlMEwceiV7EyrV4hx0axayeS3s+cvHS1cvtq3AkzMjI3QQMJBmTy7c0nC0yp9qqq1mkEC0X70T2MX0w0uheP4dM1W2KRJQPb4UqlcQKS8yLFiQDPkZ3/WGYK2RtNwk5wCVskjmsKXbg3uneTL7zzssS7GKdxddP5laIF7LTRvp76b4fu8FKVK0EZDH1LYPZztR78wM/nM1OCtK1ifTBvro+iJCmFfM3sXEZF7n3W6/XaiRrWhYV7XpFYC5ygMytrIFtvt3PXaJt499zBZZZWL1KMNpVeR+xkDIqUUq18v7g8EAno7sWOLIsHgN0ZVljHtjNUEiIhNDFfR7w/y3+h3DvymidzWOrrypP8PbSjz64mZNStL210L6Ah9pvC1dPMb3UzMj3bqTnwpWrmKuI5/hX/z9WgckcFRNWxaWTuKiH5QPgIxY5BbIGcAAgSMym57NGpAQPTnQE35Hln6R8VSstr6Bc5nZvqGkbeAmluy42Yg9WqAlfkdpZavf7CNRkF6aSik0QxaTJJubb9fyTM8F4XSklVsVP1VVH3rYXhLfSklWQkuvsXPfHzfHTUiv09wm8PEuaiQbyHmTlnS5p4a14IOrAZoMQUfkTckFmJcYjDR1U36bXmJaJb/WOEtLkjDm/gIwEZNgSDB8u4Z1f754YkeAs39K5U0swEifShk7TO7A5Giqo0/aEAbxKOMa9w7vTas8h8n6FKW7I+7wL4Q6PtlAEWtONUZ+lA+5KXqnaPQAiIcyDf+6+BqtcE366hvEPDAB6xlfNuwmErSSLDxrCWR7sdZpl9kH3I21bN954lhrjyG/YcgZ7KQNit4cmKTflMxkzHv2BGvlswTWGJRwc/5GB2YK377hB5zOyzhPdrF5fGM1Qe2PCprIRfjxyohggHqjRdwXOYhbc102qSC12sRlJWW2gkoJbPOOImbsk9Q9sSREtsH/TvYxxkCX6LrGCFwbePGK/Sbo5U4FYRnbroZ0i4UmJExNbB7rg08LMr4F1tUA3mZRu4oZAyPkATpPJ4CPHDruMIoxk40swEvlFlRdujimo7hccjQiKXETBsL0KxoCwJXpMedYtV8s1L8YocXOTMKRSmy3DiTUoWQOhdG5TYL1WET9np0t76BwfJhZ75TA8ZyXfzxEfw785OBz75G/yQhwqussln3+p15hVJAChQBkUQstI0tQflVQM/tKRLqs0BXD3R3xjKoBp1ia71PNxYGOOd1JDLaO2CnmbyNYgnqO8CEyk7UJQXQCG/qwS7zLN53lll/vNUDtFmSwMt9aMJzUju7stnL/XsH3n+ZtYwxGJIuB9MMqUZjJrhF6Bp+y8sd5SDiP8Bf8GQuoysYfoYQdP3Vajv7JVLSZlmAlB8wn8BKi6+TAmdK9DAHrKUss82E+RM9kOjKZGPScA0S+WnjwNSXz0jO0ZkLxwT8IeG7IfdrYhhA2dIH/oAxmwmtReWDph7PnR5SZG+VqD5XysLE5cTae44cKKHXFEpRNLQimK2NAyy1g2sLe5fCvr+Lj/u/jMDZ+ueTUVoa06+UQTS0q4CmfO08WBfpC+GGntqvnrQXNgXNkdSWUSUOU4xp6J/vI+b1kTj+X3gua8UGWxOMJTNiT0nSccBb6Z6cJjRB49nzCEHNFAyPGcg/+Z0KfG+/WPyVPpYUErkdq1fnxnGCrtod3QqoUPiEdPGSL/INIKCpTdaiLZIBePtEMqTUokgELlPGG3k9+OK1D7Mm+bihEvmxnpqt5fP2Q0imd6ArctRJFZ2sds7gfkKFFYFhQiwPMQH/xrRrvvbOVBJ8y+yM4AQxBbY2/UMOC5D4DITxTHH/zn6/As8RadoWk5nkMrI4cRNdkNcgIQewsCOxHIBT/xmE0eeDIVFqAU74jtu4+R2xcFOTSt3aUlWFKJ+Eagwf2HAtYlDQaozw4IzChbWsiv5dfigSSlwI7Ga88XbU9cqGQtNHu2P4SkWl5XMVnIGroSR3ke+96qHqNQxFM1YszVLcDKZ02K4gjhjoDfv0rLw1REqvXwBxDS85UXtAFxtvw8wvh7epxCvFp3twHxnOL+LAdGNXG3JabVR0KDqRg3j9tBuKERp/a8ACt+cRP0X8QG7DcsKrnKb/xhg/uhAdddRp8wSNWJbGt1EcqJXYglX8YrcaT0EPnS4XNx90Ods0S+MQk8hYY9TkykvAlpFcYLMRAu8sjrC28w+yOeR41orxdr987kNB03BOHHpmNQUHCkrPrVtmIyLV8Y3TR0SP4P48PzSVEykT6/LiZq7QBA897LzovorbjOGw9lznu6TAqtw7QMCLVS/wFnOsQMy3qul7ZBvosc5P1fAwMu1k0B+rrcUyF3JQuqWozjolz7VQxxeOwzx7LWFUjEsPqy4/SbP2r4Lc3zawVMzhx4KJiHhw9XnbcoGV5zWwjro6qHNfpgW2ysVXqj3w6g4BjH5F8+P7ppidhIvJzj+3A3P5xIx67x81qlCprtsDuxG/KOPnm7bl2acAR02R1i7WPns7XF0L7Hh8/2uzGwQGsrfKadt+iHPs7dx4999glpZFw5UQUmpYId6AHba0RAdkQJ3WyrGSQTn2d8yCDXnNWDBo9X9zblvlIPVjAUykLOEL/6NJW0cSnZqrUNwL57kZo8H/Ayk1zl/JB62aTR4qquS8+GmbfNuGuRs5r9AEnAk1mkfr+PWWzgUx1WSHk2pFWPOHSfa0ICoHAYnbpY9SkpcJJeSPF26T3TEkF/9Q4bV+nfDzN16adnWkm4a+5SE/0JA==,iv:xQwap5WCID1O4ISmUDceRSdrHm90r2UO1bCcsJcuMkM=,tag:JBHsA7OtjfPLnEkZOAtAdQ==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETHVBV1MwZXZyYkxrRkYw
            cDd1ZmM2NWxTSUxjUjhlQnBzUlFwVUtiL0NBCnZlRG1scnlodE9YaG9UNExEdUJl
            SDIzREdQdEs2M2NzbWF6NmdzUnNrWWMKLS0tIGtuelcvMXNFNXl2bnhXUUc4Qnlp
            Z3lqZ0VtU3k2aFBEc1NISGxaUHJjL28KeHGpJbgHGewQTgNRL3+T3lvbuDP1ZuY3
            bQGI668pWQV4/QzMJlBtNtr4RR+nAJ4aTe7wKoVJD2biNCXoXr0FbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-17T06:10:48Z"
    mac: ENC[AES256_GCM,data:xbLVZKYFwqA4/UpFCSdyR1e44iHGFAwmqxZd3o3TiMj9soCcXEXZ7WQYBO9dbo+DCxgMSyQQsHDyuIXwErXYctHJPQFxuH3q9XohRvfg7A+3j62a9M76SE0/r1BXYaogNXP1oXUySRDpnvH4Zca2+82ksYVO1jSx93si98AET6I=,iv:xg9+E2dfZfQmQwz1RpqwLkZMR6f/zQLpxqhuT4EXy4Y=,tag:6SNV4+8hP67OIeV/kot1+w==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.10.2
