apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:kqoIm3HN9BpvJLi0rv5opko=,iv:5EWS040fOJM8gGQ9K83dfH9Qo6WzIq6/AvJ8hrC8hFE=,tag:XdUG64iC93MX8Gr6V3qlqQ==,type:str]
    client_secret: ENC[AES256_GCM,data:15iQCvyxTTcNHOC2vUChgChHmToKy9Qr+QOFJXDR3UGgwidiKVhUzjR4w+QHyPS5W+/wH7bixsnN+07N7Vw3,iv:Z98iZSg2hr8x43Xueq6vyImz2SadIJjVbFOIr+LYVx4=,tag:YkysjIomPNJPRBZjW6QIcw==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUlJuTmZLQmJTOFhHUis0
            bXoyY3VQNjZ3bnA3VlNUcEJyWTZMN2FmdzBRCjFZdm9EVFltMDlhWDRVbVZSR1NZ
            YUpSbFFydkduMkVlS2hzTzVxeGF0ZGcKLS0tIGJrS1U4aFFWSGJHRTFLZFcxUFM2
            di9rZm54LzFxZzRUUjRDOGlmb1E1Z0UK8ATQ6Hz1KvZ5j+RAEiX1TpH4EHLTI2GI
            Zt9EiPXQsgvCCiLpqb5ljeA26U/DoqoZIWU365R9lkkT4f4L67vpvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-21T09:54:22Z"
    mac: ENC[AES256_GCM,data:aE++X+4e8eK1G4AJrweC6F8pasjkd9tUsCe3iSqyuaRffBkzMhyrOKLJxHEA0FVYXD7KDLq3jXOHH/m/YXatSK5OGSP0yFX2fPag6M+DL15kQ8E6dzpwKx8JkojcnBlthW5wz2iYHckGmxWl563D1ghOTQt/acpl4SOWgVAeF+s=,iv:7FHve0ZrLcOEwqkkKUYWdRk8qb/9zOB2d8tJ6sGFF80=,tag:KDgmUXLSBV9S3nVtmDrWRA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.10.2
