apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 8.3.8
      helm:
        valueFiles:
          - $values/argo/system/argo-cd/values.yaml
    - repoURL: https://github.com/anokfireball/cloud-as-code
      targetRevision: main
      ref: values
  destination:
    name: in-cluster
    namespace: argocd-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
