configs:
  cm:
    kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"
  params:
    application.namespaces: >-
      cert-manager-system,
      default,
      cert-manager-system,
      external-dns-system,
      nginx-system
    server.insecure: true
repoServer:
  env:
    - name: SOPS_AGE_KEY_FILE
      value: /config/sops/age/keys.txt
  volumes:
    - name: custom-tools
      emptyDir: {}
    - name: sops-age
      secret:
        secretName: sops-age
  initContainers:
    - name: install-ksops
      image: viaductoss/ksops:v4.3.3@sha256:6b5ec4b6144307f78bcddffd8f09020482836eee34cf77bf4ce8614b0452a73c
      command: ["/bin/sh", "-c"]
      args:
        - echo "Installing KSOPS...";
          mv ksops /custom-tools/;
          mv kustomize /custom-tools/;
          echo "Done.";
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
  volumeMounts:
    - mountPath: /usr/local/bin/kustomize
      name: custom-tools
      subPath: kustomize
    - mountPath: /usr/local/bin/ksops
      name: custom-tools
      subPath: ksops
    - mountPath: /config/sops/age/keys.txt
      name: sops-age
      subPath: age.agekey
