apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/oracle/oci-cloud-controller-manager/refs/tags/v1.34.0/manifests/container-storage-interface/oci-csi-controller-driver.yaml # renovate: datasource=github-tags depName=oracle/oci-cloud-controller-manager
  - https://raw.githubusercontent.com/oracle/oci-cloud-controller-manager/refs/tags/v1.34.0/manifests/container-storage-interface/oci-csi-node-driver.yaml # renovate: datasource=github-tags depName=oracle/oci-cloud-controller-manager
  - https://raw.githubusercontent.com/oracle/oci-cloud-controller-manager/refs/tags/v1.34.0/manifests/container-storage-interface/oci-csi-node-rbac.yaml # renovate: datasource=github-tags depName=oracle/oci-cloud-controller-manager
  - https://raw.githubusercontent.com/oracle/oci-cloud-controller-manager/refs/tags/v1.34.0/manifests/container-storage-interface/storage-class.yaml # renovate: datasource=github-tags depName=oracle/oci-cloud-controller-manager
patches:
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: csi-oci-node
      namespace: kube-system
    patch: |-
      - op: remove
        path: /metadata/generation
      - op: remove
        path: /metadata/annotations/deprecated.daemonset.template.generation
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: csi-oci-controller
      namespace: kube-system
    patch: |-
      - op: remove
        path: /metadata/generation
      - op: remove
        path: /metadata/annotations/deprecated.daemonset.template.generation
      - op: remove
        path: /spec/template/spec/nodeSelector
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: node-role.kubernetes.io/control-plane
                      operator: Exists
