apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster
  namespace: argocd-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    name: in-cluster
    namespace: argocd-system
  project: default
  source:
    path: argo/bootstrap
    repoURL: https://github.com/anokfireball/cloud-as-code
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: -1
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
