apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets
  namespace: argocd-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    name: in-cluster
    namespace: argocd-system
  project: default
  source:
    path: argo/secrets
    repoURL: https://github.com/anokfireball/cloud-as-code
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
