apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gatus-postgresql
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2-32@sha256:b17d21f8ec36add9b3c0ea3fb354d05f62a8fddf8ba65ae94e63ba77bc42202e
  instances: 1
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
  bootstrap:
    initdb:
      database: gatus
      owner: gatus
      secret:
        name: gatus-postgres-user
  storage:
    storageClass: oci-bv
    size: 50Gi # smallest unit offered by OCI, massive overkill for this
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatus
  namespace: argocd-system
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  sources:
    - repoURL: https://twin.github.io/helm-charts
      chart: gatus
      targetRevision: 1.4.4
      helm:
        valuesObject:
          image:
            repository: ghcr.io/twin/gatus
            # renovate: datasource=docker depName=ghcr.io/twin/gatus
            tag: "v5.31.0"
          annotations:
            reloader.stakater.com/auto: "true"
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
            path: /
            pathType: Prefix
            hosts:
              - gatus.kthxbye.cyou
            tls:
              - secretName: gatus-tls
                hosts:
                  - gatus.kthxbye.cyou
          env:
            GATUS_CONFIG_PATH: /custom/custom.yaml
            GATUS_CONFIG_FILE: /custom/custom.yaml
            SERVICE_DOMAIN:
              valueFrom:
                secretKeyRef:
                  name: gatus-secrets
                  key: SERVICE_DOMAIN
            POSTGRES_USER:
              valueFrom:
                secretKeyRef:
                  name: gatus-postgres-user
                  key: username
            POSTGRES_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: gatus-postgres-user
                  key: password
          extraVolumeMounts:
            - name: custom-config
              mountPath: /custom
              readOnly: true
              existingConfigMap: gatus-config
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
